# Generated by Django 3.1.1 on 2021-03-26 12:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex', models.CharField(max_length=7)),
                ('rgb', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('hsl_sat', models.CharField(max_length=4)),
                ('hsl_light', models.CharField(max_length=4)),
                ('hsv_sat', models.CharField(max_length=4)),
                ('hsv_val', models.CharField(max_length=4)),
                ('hue', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
