# Generated by Django 3.1.1 on 2021-03-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hsl_light',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='color',
            name='hsl_sat',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='color',
            name='hsv_sat',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='color',
            name='hsv_val',
            field=models.CharField(max_length=5),
        ),
    ]
